name: compile

on:
  push:
    branches: [ gradle, v2 ]

jobs:
  gradle:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

      # Execute Gradle commands in GitHub Actions workflows
      # => https://github.com/marketplace/actions/gradle-command
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true