name: compile

on:
  push:
    branches: [ gradle, v2 ]

jobs:
  gradle:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

      - name: Grant Execute permissions for gradlew
        run: chmod +x gradlew

      - name: Gradle Daemon Status
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --status

      - name: Stop Gradle Daemons
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --stop

      - name: Compile
        id: Compile
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
            path: bin/
